const express=require("express")
const app=express("express")
const cors=require("cors")
require("dotenv").config()
app.use(express.json())
app.use(cors())
const connectDB=require("./db")
console.log(process.env.uri)
connectDB()
app.listen(5000,()=>{console.log("server is running on the port 5000")})